version: '3.1'

services:
    web:
        image: registry.cn-hangzhou.aliyuncs.com/docker-dong/chain_tools:9e77c8
        command: sanic main:app --host=0.0.0.0 --port=8000
        deploy:
            replicas: 2

    nginx:
        image: nginx
        volumes:
            - /root/workspace/service/nginx/chain_tools.conf:/etc/nginx/conf.d/chain_tools.conf
        ports:
            - 80:80
        deploy:
            mode: global

    redis:
        image: redis
        deploy:
            replicas: 1

#secrets:
#    db_password:
#        external: true
